[tools]

neovim = "latest"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
node = "latest"
chezmoi = "latest"
usage = "latest"   # for mise completion

# "ubi:fluxcd/flux2" = { version = "latest", exe = "flux" }
