[tools]
kubectl = "latest"
neovim = "latest"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
node = "latest"
chezmoi = "latest"
usage = "latest"   # for mise completion

